# Automatically generated by configure - do not modify
TARGET_RISCV64=y
TARGET_NAME=riscv64
TARGET_BASE_ARCH=riscv
TARGET_ABI_DIR=riscv
CONFIG_SOFTMMU=y
TARGET_SUPPORTS_MTTCG=y
TARGET_XML_FILES= /home/simple/xv6-labs-2020/qemu-5.1.0/gdb-xml/riscv-64bit-cpu.xml /home/simple/xv6-labs-2020/qemu-5.1.0/gdb-xml/riscv-32bit-fpu.xml /home/simple/xv6-labs-2020/qemu-5.1.0/gdb-xml/riscv-64bit-fpu.xml /home/simple/xv6-labs-2020/qemu-5.1.0/gdb-xml/riscv-64bit-csr.xml /home/simple/xv6-labs-2020/qemu-5.1.0/gdb-xml/riscv-64bit-virtual.xml
CONFIG_I386_DIS=y
CONFIG_RISCV_DIS=y
QEMU_LDFLAGS+=
QEMU_CFLAGS+=
